server:
  port: ${PORT:8085}
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,application/javascript,application/json
    min-response-size: 1024

spring:
  application:
    name: ruralroots-backend
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:h2:mem:ruralrootsdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=PostgreSQL}
    driverClassName: ${SPRING_DATASOURCE_DRIVER:org.h2.Driver}
    username: ${SPRING_DATASOURCE_USERNAME:sa}
    password: ${SPRING_DATASOURCE_PASSWORD:}
    hikari:
      pool-name: RuralRootsHikariCPPool
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000
      max-lifetime: 1200000
      leak-detection-threshold: 15000
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
  sql:
    init:
      mode: never
  h2:
    console:
      enabled: ${H2_CONSOLE_ENABLED:true}
      path: /h2-console
  jpa:
    database-platform: ${SPRING_JPA_DATABASE_PLATFORM:org.hibernate.dialect.H2Dialect}
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:validate}
    show-sql: false
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
  expirationMs: ${JWT_EXPIRATION_MS:2592000000} # 30 days

twilio:
  account:
    sid: ${TWILIO_ACCOUNT_SID:MOCK_TWILIO_SID}
  auth:
    token: ${TWILIO_AUTH_TOKEN:MOCK_TWILIO_TOKEN}
  phone:
    number: ${TWILIO_PHONE_NUMBER:+15005550006}
